name: Build & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-web:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Build web (Vite)
        run: pnpm run build

      - name: Archive production build
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  # برای build دسکتاپ (Tauri) فقط روی لینوکس:
  build-tauri:
    runs-on: ubuntu-latest
    needs: build-web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Tauri CLI
        run: pnpm add -g @tauri-apps/cli

      - name: Build web (Vite)
        run: pnpm run build

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Archive Tauri build
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build
          path: src-tauri/target/release/bundle
